service: books-service
frameworkVersion: '3'

functions:
  api:
    handler: dist/main-serverless.handler
    events:
      - http:
          path: /ping
          method: GET
      - http:
          path: '{proxy+}'
          method: ANY
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-east-1:305236862353:userpool/us-east-1_SbntYuiaa
            scopes:
              - users/test

provider: ${file(./serverless/provider.yml)}

plugins: ${file(./serverless/plugins.yml)}

resources:
  - ${file(./serverless/resources.yml)}
